-- V4__seed_symbols.sql: Seed all 100 MVP engineering component classes across Industrial, Electrical, and Hydraulic domains

-- Industrial Domain (30 classes)
INSERT INTO symbols (id, symbol_id, entity_class, domain, svg_path, default_tag_prefix, description) VALUES
(gen_random_uuid(), 'RESERVOIR', 'RESERVOIR', 'industrial', '/assets/symbols/industrial/reservoir.svg', 'TK', 'Fluid storage reservoir'),
(gen_random_uuid(), 'CENTRIFUGAL_PUMP', 'CENTRIFUGAL_PUMP', 'industrial', '/assets/symbols/industrial/pump_centrifugal.svg', 'P', 'Centrifugal fluid pump'),
(gen_random_uuid(), 'GEAR_PUMP', 'GEAR_PUMP', 'industrial', '/assets/symbols/industrial/pump_gear.svg', 'P', 'Positive displacement gear pump'),
(gen_random_uuid(), 'STORAGE_TANK', 'STORAGE_TANK', 'industrial', '/assets/symbols/industrial/tank_storage.svg', 'T', 'Atmospheric or pressurized storage tank'),
(gen_random_uuid(), 'HEAT_EXCHANGER', 'HEAT_EXCHANGER', 'industrial', '/assets/symbols/industrial/heat_exchanger.svg', 'E', 'Shell and tube heat exchanger'),
(gen_random_uuid(), 'FILTER', 'FILTER', 'industrial', '/assets/symbols/industrial/filter.svg', 'F', 'Inline process fluid filter'),
(gen_random_uuid(), 'GATE_VALVE', 'GATE_VALVE', 'industrial', '/assets/symbols/industrial/valve_gate.svg', 'GV', 'Isolation gate valve'),
(gen_random_uuid(), 'BALL_VALVE', 'BALL_VALVE', 'industrial', '/assets/symbols/industrial/valve_ball.svg', 'BV', 'Quarter-turn ball valve'),
(gen_random_uuid(), 'BUTTERFLY_VALVE', 'BUTTERFLY_VALVE', 'industrial', '/assets/symbols/industrial/valve_butterfly.svg', 'BFV', 'Wafer butterfly valve'),
(gen_random_uuid(), 'CHECK_VALVE', 'CHECK_VALVE', 'industrial', '/assets/symbols/industrial/valve_check.svg', 'CV', 'Non-return check valve'),
(gen_random_uuid(), 'PRESSURE_RELIEF_VALVE', 'PRESSURE_RELIEF_VALVE', 'industrial', '/assets/symbols/industrial/valve_prv.svg', 'PRV', 'Safety pressure relief valve'),
(gen_random_uuid(), 'CONTROL_VALVE', 'CONTROL_VALVE', 'industrial', '/assets/symbols/industrial/valve_control.svg', 'FCV', 'Modulating flow control valve'),
(gen_random_uuid(), 'PROCESS_UNIT', 'PROCESS_UNIT', 'industrial', '/assets/symbols/industrial/process_unit.svg', 'PU', 'Generic reactor or process vessel'),
(gen_random_uuid(), 'PIPE', 'PIPE', 'industrial', '/assets/symbols/industrial/pipe.svg', 'L', 'Process piping line'),
(gen_random_uuid(), 'FLOW_METER', 'FLOW_METER', 'industrial', '/assets/symbols/industrial/flow_meter.svg', 'FIT', 'Flow rate transmitter/meter'),
(gen_random_uuid(), 'PRESSURE_GAUGE', 'PRESSURE_GAUGE', 'industrial', '/assets/symbols/industrial/pressure_gauge.svg', 'PI', 'Local pressure indicator'),
(gen_random_uuid(), 'TEMPERATURE_SENSOR', 'TEMPERATURE_SENSOR', 'industrial', '/assets/symbols/industrial/temp_sensor.svg', 'TE', 'Temperature element/RTD'),
(gen_random_uuid(), 'LEVEL_INDICATOR', 'LEVEL_INDICATOR', 'industrial', '/assets/symbols/industrial/level_indicator.svg', 'LI', 'Tank level gauge/indicator'),
(gen_random_uuid(), 'MIXER', 'MIXER', 'industrial', '/assets/symbols/industrial/mixer.svg', 'MX', 'Inline fluid mixer'),
(gen_random_uuid(), 'SEPARATOR', 'SEPARATOR', 'industrial', '/assets/symbols/industrial/separator.svg', 'SEP', 'Three-phase fluid separator'),
(gen_random_uuid(), 'COMPRESSOR', 'COMPRESSOR', 'industrial', '/assets/symbols/industrial/compressor.svg', 'K', 'Gas compressor unit'),
(gen_random_uuid(), 'BLOWER', 'BLOWER', 'industrial', '/assets/symbols/industrial/blower.svg', 'B', 'Air/gas aeration blower'),
(gen_random_uuid(), 'EJECTOR', 'EJECTOR', 'industrial', '/assets/symbols/industrial/ejector.svg', 'EJ', 'Steam/fluid jet ejector'),
(gen_random_uuid(), 'AGITATOR', 'AGITATOR', 'industrial', '/assets/symbols/industrial/agitator.svg', 'AG', 'Tank mechanical agitator'),
(gen_random_uuid(), 'CYCLONE', 'CYCLONE', 'industrial', '/assets/symbols/industrial/cyclone.svg', 'CY', 'Cyclone particulate separator'),
(gen_random_uuid(), 'FEED_TANK', 'FEED_TANK', 'industrial', '/assets/symbols/industrial/feed_tank.svg', 'V', 'Chemical feed tank'),
(gen_random_uuid(), 'DISTILLATION_COLUMN', 'DISTILLATION_COLUMN', 'industrial', '/assets/symbols/industrial/column.svg', 'C', 'Distillation/fractionation column'),
(gen_random_uuid(), 'STEAM_TRAP', 'STEAM_TRAP', 'industrial', '/assets/symbols/industrial/steam_trap.svg', 'ST', 'Condensate steam trap'),
(gen_random_uuid(), 'FLAPPER_VALVE', 'FLAPPER_VALVE', 'industrial', '/assets/symbols/industrial/flapper_valve.svg', 'FV', 'Non-return flapper valve'),
(gen_random_uuid(), 'STRAINER', 'STRAINER', 'industrial', '/assets/symbols/industrial/strainer.svg', 'STR', 'Y-type pipeline strainer');

-- Electrical Domain (35 classes)
INSERT INTO symbols (id, symbol_id, entity_class, domain, svg_path, default_tag_prefix, description) VALUES
(gen_random_uuid(), 'MOTOR', 'MOTOR', 'electrical', '/assets/symbols/electrical/motor.svg', 'M', 'AC/DC Electric motor'),
(gen_random_uuid(), 'GENERATOR', 'GENERATOR', 'electrical', '/assets/symbols/electrical/generator.svg', 'GEN', 'Electrical power generator'),
(gen_random_uuid(), 'TRANSFORMER', 'TRANSFORMER', 'electrical', '/assets/symbols/electrical/transformer.svg', 'T', 'Step-up/step-down transformer'),
(gen_random_uuid(), 'CIRCUIT_BREAKER', 'CIRCUIT_BREAKER', 'electrical', '/assets/symbols/electrical/circuit_breaker.svg', 'CB', 'Thermal-magnetic circuit breaker'),
(gen_random_uuid(), 'FUSE', 'FUSE', 'electrical', '/assets/symbols/electrical/fuse.svg', 'FU', 'Overcurrent protective fuse'),
(gen_random_uuid(), 'SWITCH', 'SWITCH', 'electrical', '/assets/symbols/electrical/switch.svg', 'SW', 'Manual disconnect switch'),
(gen_random_uuid(), 'RELAY', 'RELAY', 'electrical', '/assets/symbols/electrical/relay.svg', 'CR', 'Control switching relay'),
(gen_random_uuid(), 'CAPACITOR', 'CAPACITOR', 'electrical', '/assets/symbols/electrical/capacitor.svg', 'CAP', 'Power factor correction capacitor'),
(gen_random_uuid(), 'INDUCTOR', 'INDUCTOR', 'electrical', '/assets/symbols/electrical/inductor.svg', 'L', 'Smoothing line reactor/inductor'),
(gen_random_uuid(), 'RESISTOR', 'RESISTOR', 'electrical', '/assets/symbols/electrical/resistor.svg', 'R', 'Braking/load resistor'),
(gen_random_uuid(), 'VOLTMETER', 'VOLTMETER', 'electrical', '/assets/symbols/electrical/voltmeter.svg', 'VM', 'Voltage measuring meter'),
(gen_random_uuid(), 'AMMETER', 'AMMETER', 'electrical', '/assets/symbols/electrical/ammeter.svg', 'AM', 'Current measuring meter'),
(gen_random_uuid(), 'PANEL_BOARD', 'PANEL_BOARD', 'electrical', '/assets/symbols/electrical/panel_board.svg', 'PB', 'Main distribution panelboard'),
(gen_random_uuid(), 'BUS_BAR', 'BUS_BAR', 'electrical', '/assets/symbols/electrical/bus_bar.svg', 'BUS', 'Copper power distribution busbar'),
(gen_random_uuid(), 'CABLE', 'CABLE', 'electrical', '/assets/symbols/electrical/cable.svg', 'CBL', 'Power feeder cable'),
(gen_random_uuid(), 'JUNCTION_BOX', 'JUNCTION_BOX', 'electrical', '/assets/symbols/electrical/junction_box.svg', 'JB', 'Terminal junction box'),
(gen_random_uuid(), 'CONTACTOR', 'CONTACTOR', 'electrical', '/assets/symbols/electrical/contactor.svg', 'KM', 'Magnetic power contactor'),
(gen_random_uuid(), 'VFD', 'VFD', 'electrical', '/assets/symbols/electrical/vfd.svg', 'VFD', 'Variable frequency motor drive'),
(gen_random_uuid(), 'UPS', 'UPS', 'electrical', '/assets/symbols/electrical/ups.svg', 'UPS', 'Uninterruptible power supply'),
(gen_random_uuid(), 'BATTERY', 'BATTERY', 'electrical', '/assets/symbols/electrical/battery.svg', 'BAT', 'DC power battery bank'),
(gen_random_uuid(), 'DISCONNECT_SWITCH', 'DISCONNECT_SWITCH', 'electrical', '/assets/symbols/electrical/disconnect.svg', 'DS', 'Safety isolation disconnect switch'),
(gen_random_uuid(), 'OVERLOAD_RELAY', 'OVERLOAD_RELAY', 'electrical', '/assets/symbols/electrical/overload.svg', 'OL', 'Thermal motor overload relay'),
(gen_random_uuid(), 'SOLENOID', 'SOLENOID', 'electrical', '/assets/symbols/electrical/solenoid.svg', 'SOL', 'Electromagnetic actuator solenoid'),
(gen_random_uuid(), 'SIGNAL_LIGHT', 'SIGNAL_LIGHT', 'electrical', '/assets/symbols/electrical/light.svg', 'LT', 'Panel status pilot light'),
(gen_random_uuid(), 'GROUND_GRID', 'GROUND_GRID', 'electrical', '/assets/symbols/electrical/ground.svg', 'GND', 'Safety earthing ground grid'),
(gen_random_uuid(), 'CURRENT_TRANSFORMER', 'CURRENT_TRANSFORMER', 'electrical', '/assets/symbols/electrical/ct.svg', 'CT', 'Metering current transformer'),
(gen_random_uuid(), 'POTENTIAL_TRANSFORMER', 'POTENTIAL_TRANSFORMER', 'electrical', '/assets/symbols/electrical/pt.svg', 'PT', 'Metering potential transformer'),
(gen_random_uuid(), 'ISOLATION_TRANSFORMER', 'ISOLATION_TRANSFORMER', 'electrical', '/assets/symbols/electrical/iso_transformer.svg', 'IT', 'Galvanic isolation transformer'),
(gen_random_uuid(), 'LIMIT_SWITCH', 'LIMIT_SWITCH', 'electrical', '/assets/symbols/electrical/limit_switch.svg', 'LS', 'Position mechanical limit switch'),
(gen_random_uuid(), 'PUSH_BUTTON', 'PUSH_BUTTON', 'electrical', '/assets/symbols/electrical/push_button.svg', 'PB', 'Operator control pushbutton'),
(gen_random_uuid(), 'DIODE', 'DIODE', 'electrical', '/assets/symbols/electrical/diode.svg', 'D', 'Semiconductor power diode'),
(gen_random_uuid(), 'THYRISTOR', 'THYRISTOR', 'electrical', '/assets/symbols/electrical/thyristor.svg', 'SCR', 'Silicon controlled rectifier'),
(gen_random_uuid(), 'RECTIFIER', 'RECTIFIER', 'electrical', '/assets/symbols/electrical/rectifier.svg', 'REC', 'AC to DC power rectifier'),
(gen_random_uuid(), 'INVERTER', 'INVERTER', 'electrical', '/assets/symbols/electrical/inverter.svg', 'INV', 'DC to AC solar/power inverter'),
(gen_random_uuid(), 'AUTOMATIC_TRANSFER_SWITCH', 'AUTOMATIC_TRANSFER_SWITCH', 'electrical', '/assets/symbols/electrical/ats.svg', 'ATS', 'Generator automatic transfer switch');

-- Hydraulic Domain (35 classes)
INSERT INTO symbols (id, symbol_id, entity_class, domain, svg_path, default_tag_prefix, description) VALUES
(gen_random_uuid(), 'HYDRAULIC_PUMP', 'HYDRAULIC_PUMP', 'hydraulic', '/assets/symbols/hydraulic/pump_hydraulic.svg', 'HP', 'Fixed displacement hydraulic pump'),
(gen_random_uuid(), 'HYDRAULIC_MOTOR', 'HYDRAULIC_MOTOR', 'hydraulic', '/assets/symbols/hydraulic/motor_hydraulic.svg', 'HM', 'Fluid power rotary hydraulic motor'),
(gen_random_uuid(), 'CYLINDER', 'CYLINDER', 'hydraulic', '/assets/symbols/hydraulic/cylinder.svg', 'CYL', 'Double acting hydraulic cylinder'),
(gen_random_uuid(), 'HYDRAULIC_VALVE', 'HYDRAULIC_VALVE', 'hydraulic', '/assets/symbols/hydraulic/valve_hydraulic.svg', 'HV', 'Directional control fluid valve'),
(gen_random_uuid(), 'ACCUMULATOR', 'ACCUMULATOR', 'hydraulic', '/assets/symbols/hydraulic/accumulator.svg', 'ACC', 'Bladder/piston hydraulic accumulator'),
(gen_random_uuid(), 'HYDRAULIC_FILTER', 'HYDRAULIC_FILTER', 'hydraulic', '/assets/symbols/hydraulic/filter_hydraulic.svg', 'HF', 'High pressure return line filter'),
(gen_random_uuid(), 'RESERVOIR_HYDRAULIC', 'RESERVOIR_HYDRAULIC', 'hydraulic', '/assets/symbols/hydraulic/reservoir_hyd.svg', 'HTK', 'Hydraulic fluid reservoir tank'),
(gen_random_uuid(), 'FLOW_CONTROL_VALVE', 'FLOW_CONTROL_VALVE', 'hydraulic', '/assets/symbols/hydraulic/flow_control.svg', 'HFC', 'Adjustable hydraulic flow control valve'),
(gen_random_uuid(), 'CHECK_VALVE_HYD', 'CHECK_VALVE_HYD', 'hydraulic', '/assets/symbols/hydraulic/check_valve_hyd.svg', 'HCV', 'Hydraulic pilot operated check valve'),
(gen_random_uuid(), 'PRESSURE_RELIEF_HYD', 'PRESSURE_RELIEF_HYD', 'hydraulic', '/assets/symbols/hydraulic/prv_hyd.svg', 'HPRV', 'Main system hydraulic relief valve'),
(gen_random_uuid(), 'DIRECTIONAL_CONTROL_VALVE', 'DIRECTIONAL_CONTROL_VALVE', 'hydraulic', '/assets/symbols/hydraulic/dcv.svg', 'DCV', '4/3-way solenoid directional valve'),
(gen_random_uuid(), 'MANIFOLD', 'MANIFOLD', 'hydraulic', '/assets/symbols/hydraulic/manifold.svg', 'MAN', 'Hydraulic integrated circuit manifold'),
(gen_random_uuid(), 'HEAT_EXCHANGER_HYD', 'HEAT_EXCHANGER_HYD', 'hydraulic', '/assets/symbols/hydraulic/cooler_hyd.svg', 'HEH', 'Hydraulic oil air/water cooler'),
(gen_random_uuid(), 'PRESSURE_GAUGE_HYD', 'PRESSURE_GAUGE_HYD', 'hydraulic', '/assets/symbols/hydraulic/gauge_hyd.svg', 'HPI', 'Hydraulic system pressure gauge'),
(gen_random_uuid(), 'PROPORTIONAL_VALVE', 'PROPORTIONAL_VALVE', 'hydraulic', '/assets/symbols/hydraulic/proportional.svg', 'PV', 'Electro-hydraulic proportional valve'),
(gen_random_uuid(), 'SERVO_VALVE', 'SERVO_VALVE', 'hydraulic', '/assets/symbols/hydraulic/servo.svg', 'SV', 'Precision electro-hydraulic servo valve'),
(gen_random_uuid(), 'PRESSURE_REDUCING_VALVE', 'PRESSURE_REDUCING_VALVE', 'hydraulic', '/assets/symbols/hydraulic/reducing.svg', 'PRD', 'Sub-circuit pressure reducing valve'),
(gen_random_uuid(), 'COUNTERBALANCE_VALVE', 'COUNTERBALANCE_VALVE', 'hydraulic', '/assets/symbols/hydraulic/counterbalance.svg', 'CBV', 'Load-holding counterbalance valve'),
(gen_random_uuid(), 'BRAKE_VALVE', 'BRAKE_VALVE', 'hydraulic', '/assets/symbols/hydraulic/brake_valve.svg', 'BKV', 'Hydraulic motor braking valve'),
(gen_random_uuid(), 'SEQUENCE_VALVE', 'SEQUENCE_VALVE', 'hydraulic', '/assets/symbols/hydraulic/sequence.svg', 'SQV', 'Actuator timing sequence valve'),
(gen_random_uuid(), 'UNLOADING_VALVE', 'UNLOADING_VALVE', 'hydraulic', '/assets/symbols/hydraulic/unloading.svg', 'ULV', 'Accumulator unloading relief valve'),
(gen_random_uuid(), 'SHUTTLE_VALVE', 'SHUTTLE_VALVE', 'hydraulic', '/assets/symbols/hydraulic/shuttle.svg', 'SHV', 'OR logic hydraulic shuttle valve'),
(gen_random_uuid(), 'QUICK_DISCONNECT', 'QUICK_DISCONNECT', 'hydraulic', '/assets/symbols/hydraulic/quick_disconnect.svg', 'QD', 'Quick disconnect fluid coupling'),
(gen_random_uuid(), 'FLUID_RESERVOIR', 'FLUID_RESERVOIR', 'hydraulic', '/assets/symbols/hydraulic/fluid_res.svg', 'RES', 'Vented hydraulic oil reservoir'),
(gen_random_uuid(), 'COOLER', 'COOLER', 'hydraulic', '/assets/symbols/hydraulic/cooler.svg', 'CLR', 'Forced air hydraulic oil cooler'),
(gen_random_uuid(), 'HEATER', 'HEATER', 'hydraulic', '/assets/symbols/hydraulic/heater.svg', 'HTR', 'Electric reservoir oil immersion heater'),
(gen_random_uuid(), 'INTENSIFIER', 'INTENSIFIER', 'hydraulic', '/assets/symbols/hydraulic/intensifier.svg', 'INT', 'Hydraulic fluid pressure intensifier'),
(gen_random_uuid(), 'ROTARY_ACTUATOR', 'ROTARY_ACTUATOR', 'hydraulic', '/assets/symbols/hydraulic/rotary_actuator.svg', 'RA', 'Helical rotary hydraulic actuator'),
(gen_random_uuid(), 'TELESCOPIC_CYLINDER', 'TELESCOPIC_CYLINDER', 'hydraulic', '/assets/symbols/hydraulic/telescopic.svg', 'TC', 'Multi-stage telescopic cylinder'),
(gen_random_uuid(), 'SINGLE_ACTING_CYLINDER', 'SINGLE_ACTING_CYLINDER', 'hydraulic', '/assets/symbols/hydraulic/single_acting.svg', 'SAC', 'Spring return single acting cylinder'),
(gen_random_uuid(), 'DOUBLE_ACTING_CYLINDER', 'DOUBLE_ACTING_CYLINDER', 'hydraulic', '/assets/symbols/hydraulic/double_acting.svg', 'DAC', 'Double rod double acting cylinder'),
(gen_random_uuid(), 'PRESSURE_SWITCH', 'PRESSURE_SWITCH', 'hydraulic', '/assets/symbols/hydraulic/press_switch.svg', 'HPS', 'Fluid line pressure electric switch'),
(gen_random_uuid(), 'FLOW_SWITCH', 'FLOW_SWITCH', 'hydraulic', '/assets/symbols/hydraulic/flow_switch.svg', 'HFS', 'Inline fluid flow electric switch'),
(gen_random_uuid(), 'OIL_LEVEL_GAUGE', 'OIL_LEVEL_GAUGE', 'hydraulic', '/assets/symbols/hydraulic/level_gauge.svg', 'LG', 'Reservoir optical oil level sight gauge'),
(gen_random_uuid(), 'HYDRAULIC_HOSE', 'HYDRAULIC_HOSE', 'hydraulic', '/assets/symbols/hydraulic/hose.svg', 'HSE', 'Flexible high pressure reinforced hose');
